packages:
  # This is an inline package to prefix the on_client_connected with the wait_until action
  # It must appear before the actual package so it becomes the orignal config and the
  # on_client_connected list from the package config is appended onto this one.
  va_connected_wait_for_ble:
    voice_assistant:
      on_client_connected:
        - wait_until:
            not: ble.enabled
        - delay: 2s
    wifi:
      on_disconnect:
        - ble.enable:
  voice-kit: !include voice-kit.yaml

esphome:
  project:
    name: esphome.voice-kit
    version: dev

ota:
  - platform: http_request
    id: ota_http_request

http_request:

update:
  - platform: http_request
    name: None
    id: update_http_request
    source: https://firmware.esphome.io/voice-kit/esphome-voice-kit/manifest.json

dashboard_import:
  package_import_url: github://esphome/voice-kit/voice-kit.yaml

wifi:
  on_connect:
    - delay: 5s  # Gives time for improv results to be transmitted
    - ble.disable:
    - script.execute: control_leds

improv_serial:

esp32_improv:
  authorizer: center_button

button:
  # TODO: Remove before launch, added for testing/development
  - platform: template
    name: Check for update
    entity_category: diagnostic
    on_press:
      - component.update: update_http_request
  # TODO: Remove before launch, added for testing/development
  - platform: template
    name: Perform Update
    entity_category: diagnostic
    on_press:
      - update.perform:
          id: update_http_request
          force_update: true
