name: YAML lint

on:
  push:
    branches: [main]
    paths:
      - "**.yaml"
      - "**.yml"
  pull_request:

jobs:
  yamllint:
    name: 🧹 yamllint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out configuration from GitHub
        uses: actions/checkout@v6.0.1
      - name: 🚀 Run yamllint
        run: yamllint --strict .
